###
#TODO:
#MVN build (check)
#Spin up Tomcat(CHECK)
#Spin up postgres(CHECK)
#Add environment
#Add GeoServer
#Add depends_on
#Add Network
#ReverseProxy
###

version: '3.9'

services:
  db:
    image: postgis/postgis
    container_name: db_dova
    restart: always
    environment:
      POSTGRES_PASSWORD: <@prod_pass@>
    ports:
      - "5432:5432"
    networks:
        - kargeo-network
    volumes:
      - db_files:/var/lib/postgresql/data
  web:
    container_name: web_dova
    build:
        context: .
        dockerfile: /dockerfiles/web.Dockerfile
    ports:
      - "8080:8080"
    networks:
        - kargeo-network
  geoserver:
    container_name: geoserver_dova
    build:
        context: .
        dockerfile: ./dockerfiles/geoserver.Dockerfile
    ports:
      - "8080:8080"
    # networks:
    #     - kargeo-network
  proxy:
    restart: always
    container_name: proxy_dova
    networks:
      - kargeo-network    
    ports:
      - "80:80"
    build:
        context: .
        dockerfile: /dockerfiles/proxy.Dockerfile  
    volumes:
      - proxy_files:/etc/nginx/

  mail:
    image: bytemark/smtp
    container_name: mail_dova
    restart: always
    networks:
        - kargeo-network
volumes:
  db_files:
    external: true
  proxy_files:
    external: true

networks:
  kargeo-network:
    driver: bridge