#!/bin/bash
set -x
echo "test"

if [ "$1" = tomcat ]; then
  search="<@URL@>"
  url=http://127.0.0.1
  case $DOCKER_ENV in
  acc)
    url=https://acc.kargeotool.nl
    ;;
  prod)
    url=https://kargeotool.nl
    ;;
  esac
  sed -i "s|$search|$url|g" /usr/local/tomcat/webapps/kargeotool/META-INF/context.xml
  exec catalina.sh run
fi
#exec "$@"